import { RouterProvider } from "@tanstack/react-router"
import React from "react"

// Import the auto-generated router from the macro
// In a real Bun app with macro support, you would use:
// import { router } from './routes.macro'

// For demo purposes, here's how the generated router would be used:
/*
import {
  createRootRoute,
  createRoute,
  createRouter,
  createHashHistory,
} from '@tanstack/react-router'

// This would be auto-generated by the macro:
const router = createRouter({
  routeTree: rootRoute.addChildren([...]),
  history: createHashHistory(),
})
*/

// Create a basic app component
export function App() {
  return (
    <div className="app">
      {/* <RouterProvider router={router} /> */}
      <div>
        <h1>File-Based Routing Demo</h1>
        <p>This demonstrates the file-based routing structure.</p>
        <p>
          In a real app with Bun macro support, the router would be
          auto-generated.
        </p>
      </div>
    </div>
  )
}

export default App
