/**
 * Generated by effect-start. DO NOT EDIT.
 */
import type * as FileRouter from "effect-start/FileRouter"

const routes = {
  "/": [
    () => import("./layer.tsx"),
    () => import("./route.tsx"),
  ],
  "/chat": [
    () => import("./layer.tsx"),
    () => import("./chat/route.tsx"),
  ],
  "/data.json": [
    () => import("./layer.tsx"),
    () => import("./data.json/route.ts"),
  ],
  "/dev": [
    () => import("./layer.tsx"),
    () => import("./dev/route.ts"),
  ],
  "/chat/about": [
    () => import("./layer.tsx"),
    () => import("./chat/about/route.tsx"),
  ],
} satisfies FileRouter.FileRoutes

export default routes

declare module "effect-start/dev" {
  export interface Routes extends Omit<typeof routes, never> {}
}
