/**
 * Generated by effect-start. DO NOT EDIT.
 */
const routes = {
  "/": [
    () => import("./layer.tsx"),
    () => import("./route.tsx"),
  ],
  "/dev": [
    () => import("./layer.tsx"),
    () => import("./dev/route.ts"),
  ],
} as const

export default routes

declare module "effect-start/dev" {
  export interface Routes extends Omit<typeof routes, never> {}
}
