/**
 * Generated by effect-start. DO NOT EDIT.
 */

const routes = {
  "/": [
    () => import("./layer.tsx"),
    () => import("./route.tsx"),
  ],
  "/chat": [
    () => import("./layer.tsx"),
    () => import("./chat/route.tsx"),
  ],
  "/data.json": [
    () => import("./layer.tsx"),
    () => import("./data.json/route.ts"),
  ],
  "/dev": [
    () => import("./layer.tsx"),
    () => import("./dev/route.ts"),
  ],
  "/chat/about": [
    () => import("./layer.tsx"),
    () => import("./chat/about/route.tsx"),
  ],
  "/chat/send": [
    () => import("./layer.tsx"),
    () => import("./chat/send/route.tsx"),
  ],
  "/chat/stream": [
    () => import("./layer.tsx"),
    () => import("./chat/stream/route.tsx"),
  ],
} satisfies import("effect-start/FileRouter").FileRoutes

export default routes

declare module "effect-start/dev" {
  export interface Routes extends Omit<typeof import("./.server.ts").default, never> {}
}
