/**
 * Auto-generated by effect-start.
 */

import type { Router } from "effect-start"

export const routes = [
  {
    path: "/",
    load: () => import("./route.ts"),
    layers: [
      () => import("./layer.tsx"),
    ],
  },
  {
    path: "/movies",
    load: () => import("./movies/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./movies/layer.tsx"),
    ],
  },
  {
    path: "/users",
    load: () => import("./(admin)/users/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./(admin)/layer.ts"),
    ],
  },
  {
    path: "/movies/[id]",
    load: () => import("./movies/[id]/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./movies/layer.tsx"),
    ],
  },
  {
    path: "/about/[[...section]]",
    load: () => import("./about/[[...section]]/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./about/[[...section]]/layer.tsx"),
    ],
  },
] as const
