/**
 * Auto-generated by effect-start.
 */

import type { Router } from "effect-start"

export const modules = [
  {
    path: "/",
    segments: [],
    load: () => import("./route.ts"),
    layers: [
      () => import("./layer.tsx"),
    ],
  },
  {
    path: "/movies",
    segments: [
      { literal: "movies" },
    ],
    load: () => import("./movies/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./movies/layer.tsx"),
    ],
  },
  {
    path: "/users",
    segments: [
      { group: "admin" },
      { literal: "users" },
    ],
    load: () => import("./(admin)/users/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./(admin)/layer.ts"),
    ],
  },
  {
    path: "/movies/[id]",
    segments: [
      { literal: "movies" },
      { param: "id" },
    ],
    load: () => import("./movies/[id]/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./movies/layer.tsx"),
    ],
  },
  {
    path: "/about/[[...section]]",
    segments: [
      { literal: "about" },
      { rest: "section", optional: true },
    ],
    load: () => import("./about/[[...section]]/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./about/[[...section]]/layer.tsx"),
    ],
  },
] as const
