/**
 * Generated by effect-start. DO NOT EDIT.
 */
import type * as FileRouter from "effect-start/FileRouter"

const routes = {
  "/": [
    () => import("./layer.tsx"),
    () => import("./route.tsx"),
  ],
  "/:owner": [
    () => import("./layer.tsx"),
    () => import("./[owner]/route.tsx"),
  ],
  "/search": [
    () => import("./layer.tsx"),
    () => import("./search/route.tsx"),
  ],
  "/:owner/:repo": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/route.tsx"),
  ],
  "/orgs/:org": [
    () => import("./layer.tsx"),
    () => import("./orgs/[org]/route.tsx"),
  ],
  "/:owner/:repo/commits": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/commits/route.tsx"),
  ],
  "/:owner/:repo/contributors": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/contributors/route.tsx"),
  ],
  "/:owner/:repo/issues": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/issues/route.tsx"),
  ],
  "/:owner/:repo/pulls": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/pulls/route.tsx"),
  ],
  "/:owner/:repo/commit/:sha": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/commit/[sha]/route.tsx"),
  ],
  "/:owner/:repo/issues/:number": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/issues/[number]/route.tsx"),
  ],
  "/:owner/:repo/pulls/:number": [
    () => import("./layer.tsx"),
    () => import("./[owner]/[repo]/pulls/[number]/route.tsx"),
  ],
} satisfies FileRouter.FileRoutes

export default routes

declare module "effect-start/dev" {
  export interface Routes extends Omit<typeof routes, never> {}
}
