/**
 * Auto-generated by effect-start on startup and changes. Do not edit manually.
 */

export default {
  "/": [
    () => import("./route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner": [
    () => import("./[owner]/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/search": [
    () => import("./search/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo": [
    () => import("./[owner]/[repo]/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/orgs/:org": [
    () => import("./orgs/[org]/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo/commits": [
    () => import("./[owner]/[repo]/commits/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo/contributors": [
    () => import("./[owner]/[repo]/contributors/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo/issues": [
    () => import("./[owner]/[repo]/issues/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo/pulls": [
    () => import("./[owner]/[repo]/pulls/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo/commit/:sha": [
    () => import("./[owner]/[repo]/commit/[sha]/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo/issues/:number": [
    () => import("./[owner]/[repo]/issues/[number]/route.tsx"),
    () => import("./layer.tsx"),
  ],
  "/:owner/:repo/pulls/:number": [
    () => import("./[owner]/[repo]/pulls/[number]/route.tsx"),
    () => import("./layer.tsx"),
  ],
} satisfies import("effect-start/FileRouter").FileRoutes
