/**
 * Auto-generated by effect-start.
 */

import type { Router } from "effect-start"

export const modules = [
  {
    path: "/",
    segments: [],
    load: () => import("./route.ts"),
    layers: [
      () => import("./layer.tsx"),
    ],
  },
  {
    path: "/[[...frontend]]",
    segments: [
      { rest: "frontend", optional: true },
    ],
    load: () => import("./[[...frontend]]/route.ts"),
    layers: [
      () => import("./layer.tsx"),
    ],
  },
] as const
