/**
 * Auto-generated by effect-start.
 */

export const routes = [
  {
    path: "/",
    load: () => import("./route.tsx"),
    layers: [
      () => import("./layer.tsx"),
    ],
  },
  {
    path: "/[[404]]",
    load: () => import("./[[404]]/route.ts"),
    layers: [
      () => import("./layer.tsx"),
    ],
  },
  {
    path: "/admin",
    load: () => import("./admin/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./admin/layer.tsx"),
    ],
  },
  {
    path: "/admin/data.json",
    load: () => import("./admin/data.json/route.tsx"),
    layers: [
      () => import("./layer.tsx"),
      () => import("./admin/layer.tsx"),
    ],
  },
] as const
