import type { BunPlugin } from "bun"

/**
 * Bun plugin to handle dynamic modules used in `Bundle.dynamic`.
 */
export const BunBundleDynamicPlugin: BunPlugin = {
  name: "effect-bundler dynamic modules",
  setup(builder) {
    const DynamicModulePattern = /^effect-bundler\/dynamic\/\w+$/

    builder.onResolve({
      filter: DynamicModulePattern,
    }, (args) => {
      return {
        path: args.path,
      }
    })

    builder.onLoad({
      filter: DynamicModulePattern,
    }, (args) => {
      // TODO: this is only available from effect
      return {
        contents: `
/**
 * This module is generated by effect-bundler.
 */

export const artifacts = {
}

export const resolve = (url) => {
  return url
}

export const getArtifact = (path) => {
  const artifact = artifacts[path]

  return new Blob([artifact], {
    type: artifact.type,
  })
}
`.trim(),
        loader: "js" as const,
      }
    })
  },
}
