import * as FileSystem from "./FileSystem.ts"
import * as test from "bun:test"
import { MemoryFileSystem } from "effect-memfs"
import * as Effect from "effect/Effect"
import * as NFs from "node:fs"
import * as NPath from "node:path"
import * as FileRouter from "./FileRouter.ts"
import * as FileRouterCodegen from "./FileRouterCodegen.ts"
import * as NodeFileSystem from "./node/NodeFileSystem.ts"
import { effectFn } from "./testing"

const Files = {
  "/routes/about/layer.tsx": "",
  "/routes/about/route.tsx": "",
  "/routes/users/route.tsx": "",
  "/routes/users/layer.tsx": "",
  "/routes/users/[userId]/route.tsx": "",
  "/routes/layer.tsx": "",
}

const effect = effectFn()

test.it("walks routes", () =>
  effect(function*() {
    const files = yield* FileRouter.walkRoutesDirectory("/routes").pipe(
      Effect.provide(MemoryFileSystem.layerWith(Files)),
    )

    test
      .expect(files.map(v => v.modulePath))
      .toEqual([
        "/layer.tsx",
        "/about/layer.tsx",
        "/about/route.tsx",
        "/users/layer.tsx",
        "/users/route.tsx",
        "/users/[userId]/route.tsx",
      ])
  }))

test.it("walks routes with rest", () =>
  effect(function*() {
    const files = yield* FileRouter.walkRoutesDirectory("/routes").pipe(
      Effect.provide(
        MemoryFileSystem.layerWith({
          ...Files,
          "/routes/[[rest]]/route.tsx": "",
          "/routes/users/[[path]]/route.tsx": "",
        }),
      ),
    )

    test
      .expect(files.map(v => v.modulePath))
      .toEqual([
        "/layer.tsx",
        "/about/layer.tsx",
        "/about/route.tsx",
        "/users/layer.tsx",
        "/users/route.tsx",
        "/users/[userId]/route.tsx",
        "/users/[[path]]/route.tsx",
        "/[[rest]]/route.tsx",
      ])
  }))

test.it("walks routes with groups", () =>
  effect(function*() {
    const files = yield* FileRouter.walkRoutesDirectory("/routes").pipe(
      Effect.provide(
        MemoryFileSystem.layerWith({
          "/routes/users/route.tsx": "",
          "/routes/(admin)/layer.tsx": "",
          "/routes/(admin)/users/manage/route.tsx": "",
        }),
      ),
    )

    test
      .expect(files.map(v => ({ modulePath: v.modulePath, routePath: v.routePath })))
      .toEqual([
        { modulePath: "/(admin)/layer.tsx", routePath: "/" },
        { modulePath: "/users/route.tsx", routePath: "/users" },
        { modulePath: "/(admin)/users/manage/route.tsx", routePath: "/users/manage" },
      ])
  }))

test.describe("codegen generates server.gen.ts by default", () => {
  const tmpDir = NPath.join(import.meta.dirname, ".tmp-test-routes")

  test.beforeAll(() => {
    NFs.rmSync(tmpDir, { recursive: true, force: true })
    NFs.mkdirSync(NPath.join(tmpDir, "about"), { recursive: true })
    NFs.mkdirSync(NPath.join(tmpDir, "users"), { recursive: true })
    NFs.writeFileSync(
      NPath.join(tmpDir, "about/route.tsx"),
      "export default []",
    )
    NFs.writeFileSync(
      NPath.join(tmpDir, "users/route.tsx"),
      "export default []",
    )
  })

  test.afterAll(() => {
    NFs.rmSync(tmpDir, { recursive: true, force: true })
  })

  test.it("update generates server.gen.ts", () =>
    Effect
      .gen(function*() {
        yield* FileRouterCodegen.update(tmpDir)

        const fs = yield* FileSystem.FileSystem
        const exists = yield* fs.exists(NPath.join(tmpDir, "server.gen.ts"))

        test
          .expect(exists)
          .toBe(true)

        const content = yield* fs.readFileString(
          NPath.join(tmpDir, "server.gen.ts"),
        )

        test
          .expect(content)
          .toContain("Auto-generated by effect-start")
        test
          .expect(content)
          .toContain(`"/about":`)
        test
          .expect(content)
          .toContain(`"/users":`)
      })
      .pipe(
        Effect.provide(NodeFileSystem.layer),
        Effect.runPromise,
      ))

  test.it("generates new server.gen.ts", () =>
    Effect
      .gen(function*() {
        const genPath = NPath.join(tmpDir, "server.gen.ts")
        NFs.rmSync(genPath, { force: true })

        yield* FileRouterCodegen.dump(tmpDir)

        const fs = yield* FileSystem.FileSystem
        const exists = yield* fs.exists(genPath)

        test
          .expect(exists)
          .toBe(true)
      })
      .pipe(
        Effect.provide(NodeFileSystem.layer),
        Effect.runPromise,
      ))
})
